import { PermissionType } from "#src/api/system/role/types";

/** Map of categories and their respective permission keys */
export const PERMISSION_GROUPS: Record<string, PermissionType[]> = {
	USER: [
		PermissionType.MenuUser,
		PermissionType.ViewUserDetail,
		PermissionType.CreateUser,
		PermissionType.UpdateUser,
		PermissionType.DeleteUser,
	],
	ROLE: [
		PermissionType.MenuRole,
		PermissionType.ViewRoleDetail,
		PermissionType.CreateRole,
		PermissionType.UpdateRole,
		PermissionType.DeleteRole,
	],
	DEPARTMENT: [
		PermissionType.MenuDeparment,
		PermissionType.ViewDeparmentDetail,
		PermissionType.CreateDeparment,
		PermissionType.UpdateDeparment,
		PermissionType.DeleteDeparment,
	],
	PROJECT: [
		PermissionType.MenuProject,
		PermissionType.ViewProjectDetail,
		PermissionType.CreateProject,
		PermissionType.UpdateProject,
		PermissionType.DeleteProject,
	],
	TASK: [
		PermissionType.MenuTask,
		PermissionType.ViewTaskDetail,
		PermissionType.CreateTask,
		PermissionType.UpdateTask,
		PermissionType.DeleteTask,
		PermissionType.AssignTask,
	],
	GROUP: [
		PermissionType.MenuGroup,
		PermissionType.ViewGroupDetail,
		PermissionType.CreateGroup,
		PermissionType.UpdateGroup,
		PermissionType.DeleteGroup,
	],
	CATEGORY: [
		PermissionType.MenuCategory,
		PermissionType.ViewCategoryDetail,
		PermissionType.CreateCategory,
		PermissionType.UpdateCategory,
		PermissionType.DeleteCategory,
	],
	REQUEST_TYPE: [
		PermissionType.MenuRequestType,
		PermissionType.ViewRequestTypeDetail,
		PermissionType.CreateRequestType,
		PermissionType.UpdateRequestType,
		PermissionType.DeleteRequestType,
	],
	WORKFLOW_SETTING: [
		PermissionType.MenuWorkflowSetting,
		PermissionType.ViewWorkflowSettingDetail,
		PermissionType.CreateWorkflowSetting,
		PermissionType.UpdateWorkflowSetting,
		PermissionType.DeleteWorkflowSetting,
		PermissionType.DeployWorkflowSetting,
	],
	WORKFLOW_INSTANCE: [
		PermissionType.MenuWorkflowInstance,
		PermissionType.ViewWorkflowInstanceDetail,
		PermissionType.CreateWorkflowInstance,
		PermissionType.UpdateWorkflowInstance,
		PermissionType.CancelWorkflowInstance,
		PermissionType.RequestToCancelWorkflowInstance,
		PermissionType.ApproveCancellationWorkflowInstance,
		PermissionType.RejectCancellationWorkflowInstance,
	],
	WORKFLOW_TASK: [
		PermissionType.MenuWorkflowTask,
		PermissionType.ViewWorkflowTaskDetail,
		PermissionType.ApproveWorkflowTask,
		PermissionType.RejectWorkflowTask,
		PermissionType.ReturnWorkflowTask,
		PermissionType.RequestChangeWorkflowTask,
		PermissionType.ApplyChangeWorkflowTask,
		PermissionType.RequestReviewWorkflowTask,
		PermissionType.SubmitReviewWorkflowTask,
	],
	WORKFLOW_DELEGATION_SETTING: [
		PermissionType.MenuWorkflowDelegationSetting,
		PermissionType.ViewWorkflowDelegationSettingDetail,
		PermissionType.CreateWorkflowDelegationSetting,
		PermissionType.UpdateWorkflowDelegationSetting,
		PermissionType.DeleteWorkflowDelegationSetting,
	],
	APP_SETTING: [
		PermissionType.MenuAppSetting,
		PermissionType.ViewAppSettingDetail,
		PermissionType.CreateAppSetting,
		PermissionType.UpdateAppSetting,
		PermissionType.DeleteAppSetting,
	],
	ACTIVITY_LOG: [
		PermissionType.MenuActivityLog,
		PermissionType.ViewActivityLogAll,
		PermissionType.ViewActivityLogDepartment,
	],
};
